/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'team-members': TeamMember;
    testimonials: Testimonial;
    packages: Package;
    properties: Property;
    'blog-posts': BlogPost;
    clients: Client;
    referrals: Referral;
    'consultation-messages': ConsultationMessage;
    'consultation-read-logs': ConsultationReadLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    'consultation-messages': ConsultationMessagesSelect<false> | ConsultationMessagesSelect<true>;
    'consultation-read-logs': ConsultationReadLogsSelect<false> | ConsultationReadLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'site-config': SiteConfig;
    'referral-settings': ReferralSetting;
    'admin-registry': AdminRegistry;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    'referral-settings': ReferralSettingsSelect<false> | ReferralSettingsSelect<true>;
    'admin-registry': AdminRegistrySelect<false> | AdminRegistrySelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Cliente: solo portal público. Interno: puede ser equipo, administrador o ambos (máx. 3 administradores en todo el sistema).
   */
  accountKind: 'client' | 'internal';
  /**
   * Acceso de equipo al panel Payload (contenido, casos, etc.). Compatible con administrador.
   */
  isStaff?: boolean | null;
  /**
   * Máximo 3 administradores en total. El primer admin queda como “principal” y solo él puede nombrar a los otros dos admins (cuentas internas).
   */
  isAdmin?: boolean | null;
  /**
   * Se genera automáticamente para clientes del portal.
   */
  referralCode?: string | null;
  totalReferralEarnings?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Equipo visible en /sobre-nosotros
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  title: string;
  photo: number | Media;
  bio?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  whatsapp?: string | null;
  facebook?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  photo?: (number | null) | Media;
  quote: string;
  nationality?: string | null;
  rating?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paquetes de servicios en /servicios
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  price: number;
  billingNote?: string | null;
  features?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  highlighted?: boolean | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Listados para /hogar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  slug: string;
  /**
   * División territorial oficial (31 provincias + Distrito Nacional). Elige el municipio; la etiqueta incluye la provincia.
   */
  rdDivision:
    | 'distrito-nacional__distrito-nacional-santo-domingo'
    | 'azua__azua-de-compostela'
    | 'azua__estebania'
    | 'azua__guayabal'
    | 'azua__las-charcas'
    | 'azua__las-yayas-de-viajama'
    | 'azua__padre-las-casas'
    | 'azua__peralta'
    | 'azua__pueblo-viejo'
    | 'azua__sabana-yegua'
    | 'azua__tabara-arriba'
    | 'bahoruco__neiba'
    | 'bahoruco__galvan'
    | 'bahoruco__los-rios'
    | 'bahoruco__tamayo'
    | 'bahoruco__villa-jaragua'
    | 'barahona__barahona-santa-cruz-de-barahona'
    | 'barahona__cabral'
    | 'barahona__el-penon'
    | 'barahona__enriquillo'
    | 'barahona__fundacion'
    | 'barahona__jaquimeyes'
    | 'barahona__la-cienaga'
    | 'barahona__las-salinas'
    | 'barahona__paraiso'
    | 'barahona__polo'
    | 'barahona__vicente-noble'
    | 'dajabon__dajabon'
    | 'dajabon__el-pino'
    | 'dajabon__loma-de-cabrera'
    | 'dajabon__partido'
    | 'dajabon__restauracion'
    | 'duarte__san-francisco-de-macoris'
    | 'duarte__arenoso'
    | 'duarte__castillo'
    | 'duarte__eugenio-maria-de-hostos'
    | 'duarte__las-guaranas'
    | 'duarte__pimentel'
    | 'duarte__villa-riva'
    | 'el-seibo__el-seibo-santa-cruz-de-el-seibo'
    | 'el-seibo__miches'
    | 'elias-pina__comendador'
    | 'elias-pina__banica'
    | 'elias-pina__el-llano'
    | 'elias-pina__hondo-valle'
    | 'elias-pina__juan-santiago'
    | 'elias-pina__pedro-santana'
    | 'espaillat__moca'
    | 'espaillat__cayetano-germosen'
    | 'espaillat__gaspar-hernandez'
    | 'espaillat__jamao-al-norte'
    | 'hato-mayor__hato-mayor-del-rey'
    | 'hato-mayor__el-valle'
    | 'hato-mayor__sabana-de-la-mar'
    | 'hermanas-mirabal__salcedo'
    | 'hermanas-mirabal__tenares'
    | 'hermanas-mirabal__villa-tapia'
    | 'independencia__jimani'
    | 'independencia__cristobal'
    | 'independencia__duverge'
    | 'independencia__la-descubierta'
    | 'independencia__mella'
    | 'independencia__postrer-rio'
    | 'la-altagracia__higuey-salvaleon-de-higuey'
    | 'la-altagracia__san-rafael-del-yuma'
    | 'la-romana__la-romana'
    | 'la-romana__guaymate'
    | 'la-romana__villa-hermosa'
    | 'la-vega__la-vega-concepcion-de-la-vega'
    | 'la-vega__constanza'
    | 'la-vega__jarabacoa'
    | 'la-vega__jima-abajo'
    | 'maria-trinidad-sanchez__nagua'
    | 'maria-trinidad-sanchez__cabrera'
    | 'maria-trinidad-sanchez__el-factor'
    | 'maria-trinidad-sanchez__rio-san-juan'
    | 'monsenor-nouel__bonao'
    | 'monsenor-nouel__maimon'
    | 'monsenor-nouel__piedra-blanca'
    | 'monte-cristi__monte-cristi-san-fernando-de-monte-cristi'
    | 'monte-cristi__castanuelas'
    | 'monte-cristi__guayubin'
    | 'monte-cristi__las-matas-de-santa-cruz'
    | 'monte-cristi__pepillo-salcedo'
    | 'monte-cristi__villa-vasquez'
    | 'monte-plata__monte-plata'
    | 'monte-plata__bayaguana'
    | 'monte-plata__peralvillo'
    | 'monte-plata__sabana-grande-de-boya'
    | 'monte-plata__yamasa'
    | 'pedernales__pedernales'
    | 'pedernales__oviedo'
    | 'peravia__bani'
    | 'peravia__nizao'
    | 'puerto-plata__puerto-plata'
    | 'puerto-plata__altamira'
    | 'puerto-plata__guananico'
    | 'puerto-plata__imbert'
    | 'puerto-plata__los-hidalgos'
    | 'puerto-plata__luperon'
    | 'puerto-plata__sosua'
    | 'puerto-plata__villa-isabela'
    | 'puerto-plata__villa-montellano'
    | 'samana__samana-santa-barbara-de-samana'
    | 'samana__las-terrenas'
    | 'samana__sanchez'
    | 'san-cristobal__san-cristobal'
    | 'san-cristobal__bajos-de-haina'
    | 'san-cristobal__cambita-garabitos'
    | 'san-cristobal__los-cacaos'
    | 'san-cristobal__sabana-grande-de-palenque'
    | 'san-cristobal__san-gregorio-de-nigua'
    | 'san-cristobal__villa-altagracia'
    | 'san-cristobal__yaguate'
    | 'san-jose-de-ocoa__san-jose-de-ocoa'
    | 'san-jose-de-ocoa__rancho-arriba'
    | 'san-jose-de-ocoa__sabana-larga'
    | 'san-juan__san-juan-de-la-maguana'
    | 'san-juan__bohechio'
    | 'san-juan__el-cercado'
    | 'san-juan__juan-de-herrera'
    | 'san-juan__las-matas-de-farfan'
    | 'san-juan__vallejuelo'
    | 'san-pedro-de-macoris__san-pedro-de-macoris'
    | 'san-pedro-de-macoris__consuelo'
    | 'san-pedro-de-macoris__guayacanes'
    | 'san-pedro-de-macoris__quisqueya'
    | 'san-pedro-de-macoris__ramon-santana'
    | 'san-pedro-de-macoris__san-jose-de-los-llanos'
    | 'sanchez-ramirez__cotui'
    | 'sanchez-ramirez__cevicos'
    | 'sanchez-ramirez__fantino'
    | 'sanchez-ramirez__la-mata'
    | 'santiago__santiago-de-los-caballeros'
    | 'santiago__bisono-navarrete'
    | 'santiago__janico'
    | 'santiago__licey-al-medio'
    | 'santiago__punal'
    | 'santiago__sabana-iglesia'
    | 'santiago__san-jose-de-las-matas'
    | 'santiago__tamboril'
    | 'santiago__villa-gonzalez'
    | 'santiago-rodriguez__san-ignacio-de-sabaneta'
    | 'santiago-rodriguez__los-almacigos'
    | 'santiago-rodriguez__moncion'
    | 'santo-domingo__santo-domingo-este'
    | 'santo-domingo__boca-chica'
    | 'santo-domingo__los-alcarrizos'
    | 'santo-domingo__pedro-brand'
    | 'santo-domingo__san-antonio-de-guerra'
    | 'santo-domingo__santo-domingo-norte'
    | 'santo-domingo__santo-domingo-oeste'
    | 'valverde__mao-santa-cruz-de-mao'
    | 'valverde__esperanza'
    | 'valverde__laguna-salada';
  /**
   * Texto breve visible en la ficha (barrio, urbanización, referencia).
   */
  location: string;
  price: number;
  beds?: number | null;
  baths?: number | null;
  sqm?: number | null;
  tags?: ('sea' | 'golf' | 'new' | 'investment')[] | null;
  coverImage: number | Media;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Artículos del blog (URLs /blog/[slug] cuando publiques desde aquí)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Casos de relocalización vinculados al portal de clientes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  fullName: string;
  email?: string | null;
  phone?: string | null;
  /**
   * Cliente que ve este expediente en /dashboard
   */
  portalUser?: (number | null) | User;
  caseStage?: ('intake' | 'documentation' | 'legal' | 'housing' | 'integration' | 'completed') | null;
  timeline?:
    | {
        label: string;
        description?: string | null;
        completed?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Seguimiento de referidos y comisiones
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  referrer: number | User;
  inviteeName: string;
  inviteeEmail?: string | null;
  status?: ('pending' | 'qualified' | 'paid' | 'rejected') | null;
  commissionAmount?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Formulario web o portal cliente. Para archivar: rellena «Leído el» y guarda; el texto se elimina y queda solo el registro en «Registros leídos».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-messages".
 */
export interface ConsultationMessage {
  id: number;
  source: 'public_form' | 'client_portal';
  /**
   * Solo si el mensaje viene del área de cliente.
   */
  fromUser?: (number | null) | User;
  name: string;
  phone: string;
  email: string;
  subject: string;
  body: string;
  /**
   * Al guardar con esta fecha, el mensaje se archiva (solo queda registro con datos de contacto).
   */
  readAt?: string | null;
  readBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Se crea automáticamente al marcar un mensaje como leído. No contiene el texto del mensaje.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-read-logs".
 */
export interface ConsultationReadLog {
  id: number;
  clientName: string;
  phone: string;
  email: string;
  readAt: string;
  readBy?: (number | null) | User;
  /**
   * public_form o client_portal
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null)
    | ({
        relationTo: 'consultation-messages';
        value: number | ConsultationMessage;
      } | null)
    | ({
        relationTo: 'consultation-read-logs';
        value: number | ConsultationReadLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  accountKind?: T;
  isStaff?: T;
  isAdmin?: T;
  referralCode?: T;
  totalReferralEarnings?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  linkedin?: T;
  instagram?: T;
  whatsapp?: T;
  facebook?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  photo?: T;
  quote?: T;
  nationality?: T;
  rating?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  price?: T;
  billingNote?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  ctaLabel?: T;
  highlighted?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  rdDivision?: T;
  location?: T;
  price?: T;
  beds?: T;
  baths?: T;
  sqm?: T;
  tags?: T;
  coverImage?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  portalUser?: T;
  caseStage?: T;
  timeline?:
    | T
    | {
        label?: T;
        description?: T;
        completed?: T;
        sortOrder?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  referrer?: T;
  inviteeName?: T;
  inviteeEmail?: T;
  status?: T;
  commissionAmount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-messages_select".
 */
export interface ConsultationMessagesSelect<T extends boolean = true> {
  source?: T;
  fromUser?: T;
  name?: T;
  phone?: T;
  email?: T;
  subject?: T;
  body?: T;
  readAt?: T;
  readBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-read-logs_select".
 */
export interface ConsultationReadLogsSelect<T extends boolean = true> {
  clientName?: T;
  phone?: T;
  email?: T;
  readAt?: T;
  readBy?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * Obligatorio. Se muestra en el footer y en la página de contacto.
   */
  contactEmail: string;
  /**
   * Obligatorio. Mismo número para WhatsApp (flotante) y enlace wa.me.
   */
  whatsappPhone: string;
  /**
   * Opcional. Texto visible en footer y contacto.
   */
  addressLine?: string | null;
  /**
   * Opcional. Registro Nacional del Contribuyente (República Dominicana).
   */
  rnc?: string | null;
  /**
   * Opcional. Enlace completo al perfil, ej. https://instagram.com/tu_cuenta
   */
  instagramUrl?: string | null;
  /**
   * Opcional. Enlace completo a la página, ej. https://facebook.com/tu_pagina
   */
  facebookUrl?: string | null;
  /**
   * Opcional. Pega la URL src del iframe; si está vacío, el footer usa un mapa genérico de RD.
   */
  mapEmbedUrl?: string | null;
  /**
   * Opcional. Si está vacío, la portada usa un texto por defecto.
   */
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  welcomeText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-settings".
 */
export interface ReferralSetting {
  id: number;
  commissionPercent?: number | null;
  headline?: string | null;
  body?: string | null;
  rules?:
    | {
        rule: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * El primer administrador queda registrado aquí. Solo él puede asignar el rol de administrador a otras cuentas internas (hasta 3 admins en total, incluido él).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-registry".
 */
export interface AdminRegistry {
  id: number;
  /**
   * Definido automáticamente al crear el primer admin. Solo este usuario puede promover a otros admins.
   */
  primaryAdmin?: (number | null) | User;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  contactEmail?: T;
  whatsappPhone?: T;
  addressLine?: T;
  rnc?: T;
  instagramUrl?: T;
  facebookUrl?: T;
  mapEmbedUrl?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  welcomeText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-settings_select".
 */
export interface ReferralSettingsSelect<T extends boolean = true> {
  commissionPercent?: T;
  headline?: T;
  body?: T;
  rules?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-registry_select".
 */
export interface AdminRegistrySelect<T extends boolean = true> {
  primaryAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}